@host = https://siemens-controller.herokuapp.com

###

GET {{host}}/controller

###

GET {{host}}/controller/one/variable/set?z=x

###

GET https://siemens-controller.herokuapp.com/controller/one/variable/delete?