@host = https://siemens-controller.herokuapp.com

###

GET {{host}}/controller

###

GET {{host}}/controller/one/variable/set?z=1x

###

GET {{host}}/controller/one/variable/delete?x

###

GET {{host}}/controller/four/create
